apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: test-rucio-intertwin
    image: leggerf/rucio-intertwin:0.0.0
    imagePullPolicy: Always
    #command: ['pwd']
    command: ['./get-token.sh']
  imagePullSecrets:
  - name: dockerhub
